### ISSUE TITLE
Retire GTOPO30 plugin from GeoTools

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/dromagna#2]
Following a discussion on GeoTools Devel list we should get rid of the GTOPO30 plugin since it does not work and it is almost useles.

I would actually also make sure we have a GTOPO30 reader/writer in the ImageIO-Ext GDAL plugin for I would implement it (in this case I would open a subtask).

**Comment by dromagnoli** [comment]
I have reopened it since we also need some work in GeoServer land:
I have opened this JIRA since it requires some work (cleaning up poms, appContext, dependencies, tests, coverage configs, ...)
https://osgeo-org.atlassian.net/browse/GEOS-8839
